name: ItemLocker
version: '1.0.0'
main: org.turbojax.ItemLocker
api-version: '1.21'

permissions:
  itemlocker.help:
    description: Allows users to use "/itemlocker help"
    default: true
  itemlocker.list:
    description: Allows users to list the existing locks.
    default: true
  itemlocker.lock:
    description: Allows users to create new locks.
    default: op
  itemlocker.unlock:
    description: Allows users to remove existing locks.
    default: op
  itemlocker.bypass:
    description: Allows users to bypass locks.
    default: op